version: '2'
services:
    api:
        build:  ./api
        ports:
            -   "5000:5000"
        volumes:
            -   ./api:/api
        depends_on:
            -   db
    front:
        build:  ./front
        ports:
            -   "9000:9000"
            -   "3001:3001"
        volumes:
            -   ./front:/front
        depends_on:
            -   api
    db:
        build:  ./database
        ports:
            -   "5432:5432"
        volumes:
            -   postgres_data:/var/lib/pgsql/data
volumes:
    postgres_data:
